In [1]:
import os
import PIL
import tensorflow as tf
import matplotlib.pyplot as plt
import shutil
from sklearn.model_selection import train_test_split
from keras.preprocessing.image import ImageDataGenerator
%matplotlib inline

In [35]:
train_dir = 'dataset/train'
test_dir = 'dataset/test'

In [36]:
# for class_name in classes:
#     class_path = os.path.join('assets', class_name)
#     images = os.listdir(class_path)
#     train_images, test_images = train_test_split(images, test_size= 0.2, random_state= 42)
#     train_class_dir = os.path.join(train_dir, class_name)
#     test_class_dir = os.path.join(test_dir, class_name)
#     os.makedirs(train_class_dir, exist_ok= True)
#     os.makedirs(test_class_dir, exist_ok= True)

#     for image in train_images:
#         src = os.path.join(class_path, image)
#         dst = os.path.join(train_class_dir, image)
#         shutil.copy(src, dst)

#     for image in test_images:
#         src = os.path.join(class_path, image)
#         dst = os.path.join(test_class_dir, image)
#         shutil.copy(src, dst)


In [37]:
# train_datagen = ImageDataGenerator()
# X_train = train_datagen.flow_from_directory(train_dir, target_size= (28, 28), class_mode="sparse")


Found 5036 images belonging to 10 classes.


In [38]:
# test_datagen = ImageDataGenerator()
# X_test = test_datagen.flow_from_directory(test_dir, target_size= (28, 28), class_mode= "sparse")


Found 1263 images belonging to 10 classes.


In [13]:
train, validation = tf.keras.utils.image_dataset_from_directory(
    "assets",
    labels = "inferred",
    label_mode = "int",
    color_mode = 'grayscale',
    batch_size = 32,
    image_size = (28, 28),
    validation_split = 0.2,
    subset = "both",
    seed = 2,
    )

Found 6299 files belonging to 10 classes.
Using 5040 files for training.
Using 1259 files for validation.


## Creating a CNN

In [14]:
cnn = tf.keras.models.Sequential()
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu', input_shape=(28, 28, 1)))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))
cnn.add(tf.keras.layers.Conv2D(filters=64, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))
cnn.add(tf.keras.layers.Flatten())
cnn.add(tf.keras.layers.Dense(units=64, activation='relu'))
cnn.add(tf.keras.layers.Dense(units=10, activation='softmax'))
cnn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_3 (Conv2D)           (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d_2 (MaxPoolin  (None, 13, 13, 32)        0         
 g2D)                                                            
                                                                 
 conv2d_4 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_3 (MaxPoolin  (None, 5, 5, 64)          0         
 g2D)                                                            
                                                                 
 flatten_1 (Flatten)         (None, 1600)              0         
                                                                 
 dense_2 (Dense)             (None, 64)               

In [15]:
cnn.compile(optimizer= 'adam', loss= 'sparse_categorical_crossentropy', metrics= ['accuracy'])

In [16]:
cnn.fit(x= train, validation_data= validation, epochs=10)


Epoch 1/10


158/158 [==============================] - 5s 19ms/step - loss: 3.2198 - accuracy: 0.3530 - val_loss: 1.6295 - val_accuracy: 0.4241
Epoch 2/10
158/158 [==============================] - 2s 15ms/step - loss: 1.3436 - accuracy: 0.5260 - val_loss: 1.0253 - val_accuracy: 0.6569
Epoch 3/10
158/158 [==============================] - 3s 16ms/step - loss: 0.6664 - accuracy: 0.7657 - val_loss: 0.4879 - val_accuracy: 0.8380
Epoch 4/10
158/158 [==============================] - 2s 14ms/step - loss: 0.3166 - accuracy: 0.8869 - val_loss: 0.3503 - val_accuracy: 0.8975
Epoch 5/10
158/158 [==============================] - 2s 14ms/step - loss: 0.1881 - accuracy: 0.9377 - val_loss: 0.2843 - val_accuracy: 0.9102
Epoch 6/10
158/158 [==============================] - 2s 15ms/step - loss: 0.1225 - accuracy: 0.9603 - val_loss: 0.2643 - val_accuracy: 0.9222
Epoch 7/10
158/158 [==============================] - 2s 15ms/step - loss: 0.0759 - accuracy: 0.9744 - val_loss: 0.2283 - val_accuracy: 0.9365
Epoch 8/10

In [31]:
cnn.save("number_identifier")

INFO:tensorflow:Assets written to: number_identifier\assets


INFO:tensorflow:Assets written to: number_identifier\assets


In [30]:
from keras.preprocessing import image
import cv2
import numpy as np
nums = []
for i in range(81):
    path = str(i) + ".jpg"
    test_image = image.load_img(path, target_size = (28, 28))
    test_image = image.img_to_array(test_image)
    test_image = cv2.cvtColor(test_image, cv2.COLOR_BGR2GRAY)
    test_image = np.expand_dims(test_image, axis = 0)
    result = list(cnn.predict(test_image)[0])
    nums.append(result.index(max(result)))
nums = np.reshape(nums, (9,9))
print(nums)

1/1 [==============================] - 0s 27ms/step
[[3 0 0 8 0 1 0 0 2]
 [2 0 1 0 3 0 6 0 4]
 [0 0 0 2 0 4 0 0 0]
 [8 0 9 0 0 0 1 0 6]
 [0 6 0 0 0 0 0 5 0]
 [7 0 2 0 0 0 4 0 9]
 [0 0 0 5 0 9 0 0 0]
 [9 0 4 0 8 0 7 0 5]
 [6 0 0 1 0 7 0 0 3]]
